### ISSUE TITLE
Thermostat "mode" seems to be different in /api/status and /api/config?

### ISSUE THREAD

**Issue by swerb73** [nebulous/infinitude#91] opened 2020-04-07 19:58 UTC
Is this right?

I have the mode of the system in "fanonly" but my /api/status call shows "off" while my /api/config shows "fanonly"?

**Comment by bdf0506** [comment] 2020-04-07 20:59
I believe mode means something different in each of these by design. On one screen it is showing if the general mode is set to Auto/Cool/Fan/Off. On the other it is showing the *current* operation. So it's entirely possible that on one screen it shows Auto, and the other it shows Cooling, or something similar.

**Comment by swerb73** [comment] 2020-04-07 21:02
Hmm, but if I have it fanonly or off, shouldn't they be the same since it isn't cooling or heating at that point?

**Comment by bdf0506** [comment] 2020-04-10 01:25
Not necessarily. Mode in the config screen is what the operation mode is, think of it as the mode that the thermostat is set to. In mine, right now it is set to Auto. 
Then, in the status screen, think of this as what the current operating mode is at this exact minute. In mine, right now it says off. But, if the temperature in my house raises, and the A/C kicks on, this will change to cooling. 

Are you using this with Home Assistant? If so, see this for some more background: https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup/

**Comment by nebulous** [comment] 2020-04-10 02:15
@bdf0506 nailed it.
status is "what is the thermostat doing right now" - mode in status for me right now is `off`
config is "how is the thermostat configured to operate" - mode for zone 1 for me right now is `auto`

so they aren't intended to be the same value.

**Comment by swerb73** [comment] 2020-04-13 12:48
OK, thanks guys, appreciate the insight. I'm really trying to get the system "mode" in the status call so I can show it on the thermostat interface I've built in smarttthings. Question - does it make sense to modify the /api/status result to include this (seems like it should to me at least, like it shows many of the other core system configurations? Maybe we add a different type of "mode" to differentiate between the climate mode and the currently running heat/cooling source mode?

I suppose I could rebuilt the integration I have to use /config but it seems using /status is the best way for me to get everything I need to show a thermostat?

**Comment by nebulous** [comment] 2020-04-13 14:34
Sorry @swerb73, I'm a little bit confused. `status` and `config` are really thin wrappers around what the thermostat provides, so I'd be reluctant to augment them much. Some combination of status and config endpoints encompasses basically everything about the thermostat, but if your goal is to display current thermostat status, I think the status endpoint would have all you need. It includes per-zone heat and cool setpoints and zoneconditioning(yes, of course none of the keys are consistent.. grrrf) shows idle/heating/cooling/etc.

Could you clarify what you wanted to have added to the status api? The configuration key for configuration mode?

**Comment by swerb73** [comment] 2020-04-13 14:43
Hi @nebulous, correct, I'd love to get the configuration mode into the /api/status (status API). I realize there is already a "mode" in there which reports "what is the thermostat doing right now" per your note above, but if we could find a new key, perhaps "climate_mode", or "thermostat_mode" that would report it in that API call?

**Comment by nebulous** [comment] 2022-01-11 14:08
Grooming the old threads a bit.. Did you ever come to a reasonable solution, @swerb73? I'm not familiar with smartthings' automations, but perhaps you could hit both endpoints and use whichever keys from each that you need? I'm going to close this for now, but feel free to reopen with more details as desired.

**Closed by nebulous** 2022-01-11 14:08 UTC
Labels: question, wontfix
