### ISSUE TITLE
Proxy through to the "regular" IOS app provided by Carrier's myinfiniti IOS application

### ISSUE THREAD

**Issue by ehwest** [nebulous/infinitude#28] opened 2017-01-27 20:21 UTC
Would you consider adding a proxy capability, so this infinitude web service (running on a LINUX box) acts as a man-in-the-middle so the provided IOS apps still work, while enabling me to say, add Amazon Echo Skills?

Also I'm a bit unclear about this solution.   Do I need the serial interface?  Some version of this just runs on a web server, correct?

This is fantastic....I spent a fortune on a new carrier system and the first thing they did was remove my Nest.  And of course failed to provide to me the API specification.   I complained clearly to them an open interface is REQUIRED and it was very misleading how they sold me one of those crappy myinfinity thermostats.

**Comment by sejgit** [comment] 2017-01-31 17:01
I too would love the man-in-the-middle option. Would keep the base functions even as you add your personal home automation functions.  I plan on using this to give my ISY994 system some control. I have two furnaces and the app sucks at tieing them together for invocation of any of the profiles which you tend to do at same time. Do I need two instances of this running or will I need to modify to handle more than one unit?  Also intend to add back in the geofencing I lost when I lost my Lyrics. 
Thanks again for writing this. On the above feature I am good to take a run at it; any thoughts on strategy from the guy who knows this unit so well?
Thanks again.

**Comment by nebulous** [comment] 2017-02-18 15:08
1) Infinitude is actually _designed_ to be a man in the middle. It works by inserting itself as a proxy between Carrier and your thermostat. In fact, if it works at all on your system that's because Carrier's servers have successfully responded with the data structures the thermostat requires in order to function. By default Infinitude passes requests along to Carrier at a max rate of once every 2 hours per request, but that value is set (in seconds) in the configuration file `state/infinitude.json` as value `pass_reqs` But I don't use Carrier's service/apps so it's _entirely_ possible that functionality is broken. Check your `state/` directory for logs of requests to Carrier and additional data that the Infinitude interface does not yet render (such as energy usage, heat/cool cycles etc). Request errors are also logged as `error-<timestamp>`. Occasional errors are to be expected, but consistent errors might represent a larger issue.

2) I use `ha-proxy` to pretend to be a Philips Hue bridge, and have that run scripts against the Infinitude API, so I can say "Alexa set the heat to 68" and it will do so. Hacky, but it works.

3) You do not need a serial interface, no. Infinitude initially was designed to be a replacement/augmentation to Carrier's http api, but I was interested enough in the serial protocol and additional information inside that I built a serial monitoring function. Infinitude does _not_ write to the serial bus at this time. It may in the future, but I have many other projects and responsibilities vying for my time. If a pure serial solution is your goal, try [Infinitive](https://github.com/acd/infinitive). It looks pretty great so far, though I've unfortunately not had success with it and my Infinity Touch stat

4) Thanks. I was also forced into this system from a working network thermostat (in my case a Proliphix model) and have been consistently disappointed by the heavy handed, pricey, and inferior offering from Carrier. That annoyance is what motivated me to dig around and try to improve things. I welcome any improvements you can offer.

**Comment by nebulous** [comment] 2017-02-19 17:52
The passthru functionality did indeed have at least one bug. It would work until the first reboot, then never update Carrier again. Pushed a fix.

**Closed by nebulous** 2017-02-19 17:52 UTC
